version: '3'
services:
    mariadb:
        image: mariadb:inc
        volumes:
            - /home/user42/data/mysql:/var/lib/mysql
        restart: always
        environment:
            MARIA_LOGIN: "${MARIA_LOGIN}"
            MARIA_PASS: "${MARIA_PASS}"
        ports: 
            - "3306:3306"
        build:
            context: ./requirements/mariadb
            dockerfile: Dockerfile 
        networks:
            vpcbr:
               

    wordpress:
        image: wordpress:inc
        volumes:
            - /home/user42/data/wordpress:/var/www/wordpress
        restart: always
        environment:
            WP_LOGIN: "${WP_LOGIN}"
            WP_PASS: "${WP_PASS}"
            WPU_1LOGIN: "${WPU_1LOGIN}"
            WPU_2LOGIN: "${WPU_2LOGIN}"
            WPU_1PASS: "${WPU_1PASS}"
            WPU_2PASS: "${WPU_2PASS}"
            MARIA_LOGIN: "${MARIA_LOGIN}"
            MARIA_PASS: "${MARIA_PASS}"
        depends_on:
            - mariadb
        ports:
            - "9000:9000"
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        networks:
            vpcbr:
        # links:
        #     - mariadb
    nginx:
        image: nginx:inc
        restart: always
        depends_on:
            - wordpress
        ports:
             - "443:443"
        volumes:
            - /home/user42/data/wordpress:/var/www/wordpress
        build:
            context: ./requirements/nginx
            dockerfile: Dockerfile
        # links:
        #     - wordpress
        networks:
            vpcbr:
        extra_hosts:
            - "lusehair.42.fr:127.0.0.1"
                

networks:
    vpcbr:
        driver: bridge


